# Generated by Django 4.0.2 on 2022-02-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangolab', '0002_intake_myusers_intake_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='intake_id',
        ),
    ]
