# Generated by Django 4.0.2 on 2022-02-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangolab', '0003_remove_myusers_intake_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intake',
        ),
    ]
