# Generated by Django 4.0.2 on 2022-02-08 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangolab', '0004_delete_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='myusers',
            name='intake_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='djangolab.intake'),
            preserve_default=False,
        ),
    ]
